source("common.R")

# NOTE: the NC cities break the contract implicit in all other city processing
# files; most can be sourced without assuming other files have already been
# sourced; however, in the case of NC, we process all statewide data in
# statewide.R; rather than copying the contents of this script over to every
# city, we elected to break the contract in this case and assume opp.R has
# already been sourced and we have access to opp_load_raw("nc", "statewide")
# and opp_load_clean("nc", "statewide"); this means a few things: (1) metadata
# will refer to the entire statewide metadata, i.e. loading problems, and (2)
# raw_row_number will not be unique to this file, but to NC as a whole, i.e. a
# city might contain ids 1, 5, 20, 2182, etc...but the data generated by
# statewide.R will have all ids

# VALIDATION: [YELLOW] 2008, 2009, and 2010; the Durham PD's 2015
# Annual Report only lists statistics on violent crimes, so it's hard to tell
# how traffic data stands in comparison. However, arrest totals 2013-2015 in
# the traffic data were roughly 60-80% of total vehicle theft arrests in the
# same time period according to the report, which seems reasonable.
# See TODOs in statewide.R for outstanding tasks
# TODO(phoebe): can we get missing data from 2008-2013:
# 2008 missing January data
# 2009 missing February, April, July, September, October, December
# 2010 missing February, November
# 2013 missing May
# https://app.asana.com/0/456927885748233/663459094621781
load_raw <- function(raw_data_dir, n_max) {
  d <- opp_load_raw("nc", "statewide")
  d$data <- filter(d$data, str_detect(AgencyDescription, "Durham"))
  d
}


clean <- function(d, helpers) {
  d <- opp_load_clean("nc", "statewide")
  d$data <- filter(d$data, str_detect(department_name, "Durham"))
  d
}
