source("common.R")

# NOTE: the NC cities break the contract implicit in all other city processing
# files; most can be sourced without assuming other files have already been
# sourced; however, in the case of NC, we process all statewide data in
# statewide.R; rather than copying the contents of this script over to every
# city, we elected to break the contract in this case and assume opp.R has
# already been sourced and we have access to opp_load_raw("nc", "statewide")
# and opp_load_clean("nc", "statewide"); this means a few things: (1) metadata
# will refer to the entire statewide metadata, i.e. loading problems, and (2)
# raw_row_number will not be unique to this file, but to NC as a whole, i.e. a
# city might contain ids 1, 5, 20, 2182, etc...but the data generated by
# statewide.R will have all ids

# VALIDATION: [GREEN] 2000 and 2001 have only partial data; it also appears
# that 2009 has data issues for August through December. The Fayetteville PDs
# 2015 annual report cites 57,528 traffic stops in 2015 while we have 57,816,
# representing a ~0.5% difference; this could be due to the time the report was
# compiled or when the data were collected, but is quite close.
load_raw <- function(raw_data_dir, n_max) {
  d <- opp_load_raw("nc", "statewide")
  d$data <- filter(d$data, str_detect(AgencyDescription, "Fayetteville"))
  d
}


clean <- function(d, helpers) {
  d <- opp_load_clean("nc", "statewide")
  d$data <- filter(d$data, str_detect(department_name, "Fayetteville"))
  d
}
