source("common.R")

# NOTE: the NC cities break the contract implicit in all other city processing
# files; most can be sourced without assuming other files have already been
# sourced; however, in the case of NC, we process all statewide data in
# statewide.R; rather than copying the contents of this script over to every
# city, we elected to break the contract in this case and assume opp.R has
# already been sourced and we have access to opp_load_raw("nc", "statewide")
# and opp_load_clean("nc", "statewide"); this means a few things: (1) metadata
# will refer to the entire statewide metadata, i.e. loading problems, and (2)
# raw_row_number will not be unique to this file, but to NC as a whole, i.e. a
# city might contain ids 1, 5, 20, 2182, etc...but the data generated by
# statewide.R will have all ids

# VALIDATION: [YELLOW] The Greensboro Police Department Annual Professional
# Standards Report 2015 has few traffic statistics but lists figures for calls
# for service: 243k in 2014 and 224k in 2015. This data has 39k stops in 2014
# and 28k in 2015, which seems reasonable by comparison. 2000 and 2001 only
# have partial data. There are also some random months with missing data; see
# TODOs for details

# TODO(phoebe): missing data 8/2015, 11/2015, 11/2016, and 3/2014
# https://app.asana.com/0/456927885748233/950796405221403 
load_raw <- function(raw_data_dir, n_max) {
  d <- opp_load_raw("nc", "statewide")
  d$data <- filter(d$data, str_detect(AgencyDescription, "Greensboro"))
  d
}


clean <- function(d, helpers) {
  d <- opp_load_clean("nc", "statewide")
  d$data <- filter(d$data, str_detect(department_name, "Greensboro"))
  d
}
