source("common.R")

# NOTE: the NC cities break the contract implicit in all other city processing
# files; most can be sourced without assuming other files have already been
# sourced; however, in the case of NC, we process all statewide data in
# statewide.R; rather than copying the contents of this script over to every
# city, we elected to break the contract in this case and assume opp.R has
# already been sourced and we have access to opp_load_raw("nc", "statewide")
# and opp_load_clean("nc", "statewide"); this means a few things: (1) metadata
# will refer to the entire statewide metadata, i.e.  loading problems, and (2)
# raw_row_number will not be unique to this file, but to NC as a whole, i.e. a
# city might contain ids 1, 5, 20, 2182, etc...but the data generated by
# statewide.R will have all ids

# VALIDATION: [RED] There are many missing months of data. The 2014 Raleigh
# PD Community Report has very few traffic related statistics, but on page 21
# it says "Traffic Enforcement Unit officers were responsible for 6.337 total
# charges, including 142 DWI arrests." This data shows 1,785 arrests in 2014
# (although one month is missing) and 67k stops.  It's unclear how this figures
# can be reconciled.

# TODO(phoebe): Missing data 2/2004, 2/2005, 5/2005, 10/2005, 11/2005, 3/2006,
# 8/2006, 4/2007, 11/2008, 1/2009, 11/2012, 9/2013, 11/2013, 7/2014, 10/2014,
# 10/2015
# https://app.asana.com/0/456927885748233/950796405221404
load_raw <- function(raw_data_dir, n_max) {
  d <- opp_load_raw("nc", "statewide")
  d$data <- filter(d$data, str_detect(AgencyDescription, "Raleigh"))
  d
}


clean <- function(d, helpers) {
  d <- opp_load_clean("nc", "statewide")
  d$data <- filter(d$data, str_detect(department_name, "Raleigh"))
  d
}
