source("common.R")

# NOTE: the NC cities break the contract implicit in all other city processing
# files; most can be sourced without assuming other files have already been
# sourced; however, in the case of NC, we process all statewide data in
# statewide.R; rather than copying the contents of this script over to every
# city, we elected to break the contract in this case and assume opp.R has
# already been sourced and we have access to opp_load_raw("nc", "statewide")
# and opp_load_clean("nc", "statewide"); this means a few things: (1) metadata
# will refer to the entire statewide metadata, i.e. loading problems, and (2)
# raw_row_number will not be unique to this file, but to NC as a whole, i.e. a
# city might contain ids 1, 5, 20, 2182, etc...but the data generated by
# statewide.R will have all ids

# VALIDATION: [RED] 2000 and 2001 are missing most data; there are also several
# missing months in 2014 and 2015. And while the 2015 Annual Report
# has a lot of statistics, they don't clearly align with the data here (likely
# due in part to the missing data).

# TODO(phoebe): missing data 8/2014, 1/2015, 2/2015, and 5/2015
# https://app.asana.com/0/456927885748233/668125716167089
load_raw <- function(raw_data_dir, n_max) {
  d <- opp_load_raw("nc", "statewide")
  d$data <- filter(d$data, str_detect(AgencyDescription, "Winston-Salem"))
  d
}


clean <- function(d, helpers) {
  d <- opp_load_clean("nc", "statewide")
  d$data <- filter(d$data, str_detect(department_name, "Winston-Salem"))
  d
}
