---
params:
  state: ""
  city: ""
---


```{r setup, echo = FALSE}
opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

city <- params$city
state <- params$state

read_chunk("report.R", labels = "report")
```

```{r report}
```

---
title: `r title`
---

\begin{center}
2010 Census population: `r comma_num(population)`

`r comma_num(total_rows)` rows from `r date_range[1]` to `r date_range[2]`
\end{center}

```{r by_incident_type_table, fig.align = 'left'}
by_incident_type_table
```

```{r null_rates_table}
null_rates_table
```

```{r by_year_plot}
by_year_plot
```

```{r by_year_by_month_plot}
by_year_by_month_plot
```

```{r by_year_by_day_plot, fig.height = 10}
by_year_by_day_plot
```

```{r by_year_by_day_of_week_plot, fig.height = 10}
by_year_by_day_of_week_plot
```

```{r race_pct_plot}
race_pct_plot
```

```{r reason_for_stop_top_20_plot}
reason_for_stop_top_20_plot
```

```{r search_conducted_plot}
search_conducted_plot
```

```{r search_types_plot}
search_types_plot
```

```{r contraband_found_plot}
contraband_found_plot
```

```{r contraband_found_by_race_plot}
contraband_found_by_race_plot
```

```{r citation_issued_plot}
citation_issued_plot
```

```{r arrest_made_plot}
arrest_made_plot
```

\newpage

\begin{center}
\textbf{Metadata}
\end{center}

```{r loading_problems_count_table}
loading_problems_count_table
```

```{r loading_problems_random_sample_sorted_table}
loading_problems_random_sample_sorted_table
```

\newpage

```{r missing_columns_added_table}
missing_columns_added_table
```

```{r enforce_types_table}
enforce_types_table
```

```{r sanitize_table}
sanitize_table
```
